### ISSUE TITLE
Fix bug in table_template.erb reference

### ISSUE THREAD

**Issue by jaydorsey** [jaydorsey/env_compare#26]
A user ran into this today:

    (erb):46:in `initialize': No such file or directory @ rb_sysopen - themes/table_template.erb (Errno::ENOENT)

I think it might be caused by my use of `File.new()` without specifying how that path is found (so it's relative to the context). It works on at least 2 machines, but not on one (all macOS), but definitely a bug that I need to work around

Fix the reference in both template files

**Comment by smridge** [comment]
I was _somewhat_ able to reproduce this in an `irb` session. The latest published version on my machine is `0.1.1`, which doesn't have the template. Without knowing exactly what the other person used as their command and the version, it's a bit hard to pinpoint.

Reference: https://stackoverflow.com/a/10202345

```
$ irb
gem_root = Gem::Specification.find_by_name("env_compare").gem_dir
 => "/Users/sarahridge/.rvm/gems/ruby-2.7.1/gems/env_compare-0.1.1" 
2.7.1 :003 > File.new("#{gem_root}/themes/table_template.erb")
Traceback (most recent call last):
        6: from /Users/sarahridge/.rvm/rubies/ruby-2.7.1/bin/irb:23:in `<main>'
        5: from /Users/sarahridge/.rvm/rubies/ruby-2.7.1/bin/irb:23:in `load'
        4: from /Users/sarahridge/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        3: from (irb):3
        2: from (irb):3:in `new'
        1: from (irb):3:in `initialize'
Errno::ENOENT (No such file or directory @ rb_sysopen - /Users/sarahridge/.rvm/gems/ruby-2.7.1/gems/env_compare-0.1.1/themes/table_template.erb)
```

```
$ bundle exec irb
[1] pry(main)> gem_root = Gem::Specification.find_by_name("env_compare").gem_dir
=> "/Users/sarahridge/projects/env_compare"
[2] pry(main)> File.new("#{gem_root}/themes/table_template.erb") 
=> #<File:/Users/sarahridge/projects/env_compare/themes/table_template.erb>
```

After reading up on a few things, this seems to be a known annoyance with gems. So we can attempt to do something like:

```ruby
    <% gem_root = Gem::Specification.find_by_name("env_compare").gem_dir %>
    <%= ERB.new(File.new("#{gem_root}/themes/table_template.erb").read).result(table_template.get_binding) %>
```

but it may need a bit more scrutiny.

**Comment by jaydorsey** [comment]
It would have been the last published non alpha/beta version (it was mike who ran into it)

I'll see if I can get more info on reproduction. 

I still want to looks at the file paths joining because using the path join method is more portable but you're right, we should also see if we can be sure that was the root cause

**Comment by smridge** [comment]
If Chavez happened to have it cloned separately from the install, then that was likely the issue since that's how I was able to reproduce it. Running from the cloned repo using `bundle exec` vs running from the cloned repo not using `bundle exec`.
